name: Update TMX
on:
  schedule:
    - cron: '0 0 1 * *' # Run on the first day of the month
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          pip install -r .github/scripts/requirements.txt
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Download TMX for all locales
        run: |
          python .github/scripts/download_tmx.py
      - name: Clean up errors in TMX
        run: |
          bash .github/scripts/fix_tmx.sh
      - run : git config --global user.email 'flodolo@users.noreply.github.com'
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Update TMX from Pontoon (${{ steps.date.outputs.date }})"
          branch: tmx_automation
          delete-branch: true
          title: "Update TMX from Pontoon (${{ steps.date.outputs.date }})"
